/**
 * Report PDF Generator
 * Generates and downloads a PDF from report data using jsPDF
 */

import { jsPDF } from 'jspdf';

const wrapText = (doc, text, x, y, maxWidth, lineHeight = 6) => {
  const lines = doc.splitTextToSize(text, maxWidth);
  doc.text(lines, x, y);
  return y + lines.length * lineHeight;
};

/**
 * Download a medical report as PDF
 * @param {Object} report - Report object from API
 */
export const downloadReportPdf = (report) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let y = 20;

  // Header
  doc.setFontSize(20);
  doc.setTextColor(79, 70, 229);
  doc.text('Carepluse Medical Report', margin, y);
  y += 12;

  doc.setDrawColor(100, 116, 139);
  doc.line(margin, y, pageWidth - margin, y);
  y += 12;

  // Report title
  doc.setFontSize(16);
  doc.setTextColor(30, 41, 59);
  doc.text(report.title || 'Medical Report', margin, y);
  y += 10;

  // Meta info
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);

  const reportDate = report.reportDate
    ? new Date(report.reportDate).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      })
    : 'N/A';

  doc.text(`Date: ${reportDate}`, margin, y);
  y += 6;
  doc.text(`Doctor: Dr. ${report.doctor?.name || 'Unknown'}`, margin, y);
  y += 6;

  if (report.doctor?.specialization) {
    doc.text(`Specialization: ${report.doctor.specialization}`, margin, y);
    y += 6;
  }

  if (report.patient?.name) {
    doc.text(`Patient: ${report.patient.name}`, margin, y);
    y += 6;
  }

  y += 6;
  doc.line(margin, y, pageWidth - margin, y);
  y += 12;

  // Content sections
  const addSection = (label, content) => {
    if (!content) return;

    if (y > 260) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(11);
    doc.setTextColor(79, 70, 229);
    doc.text(label, margin, y);
    y += 7;

    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    y = wrapText(doc, content, margin, y, maxWidth) + 8;
  };

  addSection('Description', report.description);
  addSection('Diagnosis', report.diagnosis);
  addSection('Prescription', report.prescription);
  addSection('Notes', report.notes);
  addSection('Report Content', report.reportContent);

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      `Generated by Carepluse · Page ${i} of ${pageCount}`,
      margin,
      doc.internal.pageSize.getHeight() - 10
    );
  }

  const filename = `report-${report.title?.replace(/\s+/g, '-').toLowerCase() || report._id}.pdf`;
  doc.save(filename);
};
